CREATE TABLE ABC
( AAA CHAR(20)
 ,BBB INT 
 );

ALTER TABLE ABC ADD CCC CHAR(20);
ALTER TABLE ABC DROP COLUMN "CCC" ;

SELECT
    * FROM ABC;
    
CREATE TABLE SQL_EMP1(
EMP_ID CHAR (8 BYTE)PRIMARY KEY,
EMP_NM NVARCHAR2(20),
ID VARCHAR2(10),
TEL VARCHAR2(10),
DEP NVARCHAR2(20)
);

CREATE TABLE SQL_CUSTOMER1(
ID VARCHAR2(10) PRIMARY KEY,
NAME NVARCHAR2(20),
EMP CHAR(8) REFERENCES SQL_EMP1(EMP_ID)
);

ALTER TABLE SQL_CUSTOMER1
ADD FOREIGN KEY (EMP) REFERENCES SQL_EMP(EMP_ID);

CREATE INDEX SQL_EMP_INDEX1 ON SQL_EMP1(DEP);

CREATE TABLE WATER1 AS SELECT * FROM SQL_TAOYUAN_WATER;

SELECT 
 SERIAL_NUMBER AS "序號" 
 ,HYDROGEN AS "氫離子濃度指數" 
 ,TURBIDITY AS "濁度" 
 ,CHLORINE AS "自由有效餘氯" FROM WATER1;
 
SELECT * FROM SQL_EMP
 WHERE DEP='系統開發部' AND EMP_NM LIKE '王%';
 
SELECT * FROM SQL_EMP
 WHERE DEP='系統開發部' OR DEP='開發系統部';
 
SELECT * FROM SQL_EMP
 WHERE(DEP='系統開發部' AND EMP_NM LIKE '王%')
 OR(DEP='開發系統部' AND EMP_NM LIKE '孫%');
 
SELECT 
 EMP_ID AS "工號"
 ,EMP_NM AS "名稱"
 ,ID AS "身分證字號"
 ,TEL AS "電話"
 ,DEP AS "部門"
 FROM SQL_EMP
 WHERE DEP='系統開發部' AND EMP_NM LIKE '王%';
 
SELECT * FROM SQL_EMP
 WHERE EMP_ID BETWEEN '00011111' AND '00055555';
 
SELECT * FROM SQL_EMP
 WHERE DEP IN ('系統開發部', '開發系統部');
 
SELECT * FROM SQL_EMP
 WHERE TEL IS NULL;
 
--P24課堂練習5-1
SELECT
SERIAL_NUMBER AS "序號"
,HYDROGEN AS "氫離子濃度指數"
,TURBIDITY AS "濁度"
,CHLORINE AS "自由有效餘氯"
FROM WATER1
WHERE 
HYDROGEN IN ('7.5', '8')
AND CHLORINE >'0.6' 
AND PLACE = 'T22' ;

--課堂練習5-2
SELECT
SERIAL_NUMBER AS "序號"
,HYDROGEN AS "氫離子濃度指數"
,TURBIDITY AS "濁度"
,CHLORINE AS "自由有效餘氯"
FROM WATER1
WHERE
(SERIAL_NUMBER BETWEEN '521' AND '529')
OR
((SERIAL_NUMBER <'521' OR SERIAL_NUMBER >'529')
AND
CHLORINE IN (0.76, 0.77, 0.66)
AND
HYDROGEN <> '7.8'
AND
TURBIDITY = '0.6' );
--課本中不是7.8但變成是

SELECT DISTINCT DEP
FROM SQL_EMP;

SELECT DISTINCT DEP, EMP_NM
 FROM SQL_EMP;
 
SELECT EMP_NM
 FROM SQL_EMP
 ORDER BY EMP_ID DESC;
 
SELECT DEP, ID, EMP_NM
 FROM SQL_EMP
 ORDER BY DEP ASC, ID DESC;
 
--課堂練習6
SELECT DISTINCT 
PLACE AS "地點"
,SERIAL_NUMBER AS "序號"
,HYDROGEN AS "氫離子濃度指數"
,TURBIDITY AS "濁度"
,CHLORINE AS "自由有效餘氯"
FROM WATER1
WHERE 
SERIAL_NUMBER BETWEEN '521' AND '529'
OR 
CHLORINE IN ('0.76', '0.77', '0.66')
AND 
HYDROGEN <> '7.8'
AND
TURBIDITY = '0.6'
ORDER BY TURBIDITY ASC, SERIAL_NUMBER DESC;

SELECT EMP_NM, ID FROM SQL_EMP
UNION ALL
SELECT NAME, ID  FROM SQL_CUSTOMER;

SELECT EMP_NM, ID FROM SQL_EMP
UNION
SELECT NAME, ID FROM SQL_CUSTOMER;

SELECT *
 FROM SQL_EMP
 WHERE EMP_ID IN (SELECT DISTINCT EMP FROM SQL_CUSTOMER);
 
--練習7
SELECT 地點, 序號, 氫離子濃度指數, 濁度, 自由有效餘氯
FROM(
    SELECT PLACE AS "地點"
    ,SERIAL_NUMBER AS "序號"
    ,HYDROGEN AS "氫離子濃度指數"
    ,TURBIDITY AS "濁度"
    ,CHLORINE AS "自由有效餘氯"
    FROM WATER1
    WHERE (SERIAL_NUMBER BETWEEN '521' AND '529')
UNION
    SELECT  
    PLACE AS "地點"
    ,SERIAL_NUMBER AS "序號"
    ,HYDROGEN AS "氫離子濃度指數"
    ,TURBIDITY AS "濁度"
    ,CHLORINE AS "自由有效餘氯"
    FROM WATER1
    WHERE
    CHLORINE IN ('0.76', '0.77', '0.66')
    AND 
    HYDROGEN <> '7.8'
    AND
    TURBIDITY = '0.6'
)
ORDER BY 濁度 ASC, 序號 DESC;

select PLACE,
    SERIAL_NUMBER,
    HYDROGEN,
    TURBIDITY,
    CHLORINE from(
 select 
     PLACE,
     SERIAL_NUMBER,
     HYDROGEN,
     TURBIDITY,
     CHLORINE,
     ROW_NUMBER() Over (Partition By PLACE Order By SERIAL_NUMBER asc) As Sort 
 from SQL_TAOYUAN_WATER 
 where SERIAL_NUMBER between 521 and 529 
 or(CHLORINE in (0.76,0.77,0.66)
 and HYDROGEN != 7.8
 and TURBIDITY = 0.6)
 order by TURBIDITY asc , SERIAL_NUMBER desc) tmp
 where tmp.Sort = 1; --只拿一個欄位
 
SELECT CUT.ID, CUT.NAME, EMP.EMP_NM
FROM SQL_CUSTOMER CUT
INNER JOIN SQL_EMP EMP ON CUT.EMP = EMP.EMP_ID;

--練習8
SELECT data.